CREATE TABLE IF NOT EXISTS users
(
    id UUID        NOT NULL PRIMARY KEY,
    nickname VARCHAR(25) NOT NULL,
    age INTEGER NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);
