app:
  name: 'go_project_template'
  version: '1.0.0'

http:
  port: '8078'

postgres:
  max_pool_size: 1
  connect_timeout: "1s"
  connect_attemp: 1

logger:
  level: "info"

grpc:
  port: "9078"

metrics:
  port: '8082'
